name: Push on DockerHub

on:
  push:
    branches: [ "master" ]

jobs:
  publish:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Set env
        run: echo "APP_VERSION=$(date +"%Y-%m-%d")" >> $GITHUB_ENV

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./
          file: Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/asparser:latest,${{ secrets.DOCKERHUB_USERNAME }}/asparser:${{ env.APP_VERSION }}
